### ISSUE TITLE
Geobuf Format: Too many options

### ISSUE THREAD

**Issue by joto** [mapbox/geobuf#32]
Looking at the `proto` file, if I interpret it correctly, I think there are too many options how the file format can actually look like. The `data_type` seems to suggest the outermost structure can be either a `FeatureCollection`, a `Feature`, a `Geometry` or a `Topology`. Is that necessary? Can't it always be a Feature Collection, possibly with just one feature in it which in turn contains one `Geometry`? I am concerned that different implementors will implement slightly different subsets of the format making implementations incompatible.

Whats the difference between the `Value`, the `properties` and the `custom_properties`? Repeating those fields in `Feature` and `Geometry` doesn't look good to me. Do we really need that? In my understanding a _feature_ is a _geometry_ plus some _attributes_. If we can put _attributes_ on the _geometry_, why is there a distinction between _feature_ and _geometry_?

Why has the `Topology` no `properties`, just `Value` and `custom_properties`? (Unlike `Feature` and `Geometry` which have all three.)

**Comment by mourner** [comment]
> The `data_type` seems to suggest the outermost structure can be either a `FeatureCollection`, a `Feature`, a `Geometry` or a `Topology`. Is that necessary? Can't it always be a Feature Collection, possibly with just one feature in it which in turn contains one `Geometry`?

This is necessary. One of the requirements of the encoding to be able encode a GeoJSON or a TopoJSON file and decode it into the same file. GeoJSON spec allows any of the types in the root, so we don't want to encode a Geometry and suddenly get a FeatureCollection when its decoded.

> Whats the difference between the `Value`, the `properties` and the `custom_properties`? Repeating those fields in `Feature` and `Geometry` doesn't look good to me. Do we really need that? In my understanding a _feature_ is a _geometry_ plus some _attributes_. If we can put _attributes_ on the _geometry_, why is there a distinction between _feature_ and _geometry_?

We need that. `Value` represents a value (which can be of different types and needs its own message type), and `properties` is a packed array of key/value pairs as `uint` — we need to store them separately for optimal compression.

`properties` encodes the feature `properties` object, while `custom_properties` encodes any arbitrary properties that are not mentioned in the GeoJSON/TopoJSON specs. We need this distinction.

Properties are encoded either in `Feature` or in `Geometry` because GeoJSON spec needs them encoded in `Feature` while TopoJSON spec needs them encoded in `Geometry`. We need to support both formats.

> Why has the `Topology` no `properties`, just `Value` and `custom_properties`? (Unlike `Feature` and `Geometry` which have all three.)

Because `Topology` object doesn't have `properties` according to the `TopoJSON` spec. But it can have arbitrary properties.

**Comment by mourner** [comment]
Reopening in case someone else has feedback on the matter.

**Comment by joto** [comment]
Could we add some kind of flag or so that says "properties were on feature" vs. "properties were on geometry" that everybody else would ignore, but somebody trying to write out the original geojson/topojson could interpret? Just brainstorming aloud here about ideas how to reduce complexity in this format.

**Comment by mourner** [comment]
TopoJSON support removed in #43, so things are much simpler now.
