### ISSUE TITLE
Command line conversion loses the properties of a FeatureCollection

### ISSUE THREAD

**Issue by slaskis** [mapbox/geobuf#59]
It looks to me [in the code](https://github.com/mapbox/geobuf/blob/master/encode.js#L102) that the properties of a FeatureCollection is written. 

So I'm thinking this might a bug:

```
echo '{"type": "FeatureCollection", "properties": {"name": "collection"}, "features": []}' \
 | ./node_modules/.bin/json2geobuf \
 | ./node_modules/.bin/geobuf2json \
 | jq .
# -> {"type":"FeatureCollection","features":[]}
```

**Comment by slaskis** [comment]
Oh I see now. [It specifically skips a `properties` field](https://github.com/mapbox/geobuf/blob/master/encode.js#L141-L142).

It this intentional though? I know a FeatureCollection doesn't have a `properties` field according to the spec but to me it makes sense to keep a similar structure of metadata. Or at least be able to. 

I'd gladly provide a PR with an added test/fixture that only checks for `type` and `features` for FeatureCollections (the fields defined according to the spec) if I'm on the right track.

**Comment by mourner** [comment]
@slaskis this looks like a bug. This routine skips certain keys because they are encoded anyway with other routines (e.g. `geometry` for different geometries types), but I didn't take into account the possibility of encoding a special key that's not used in a particular GeoJSON object (such as `properties` in FeatureCollection). We should fix this.

**Comment by slaskis** [comment]
Cool, I can give it a shot since I need it myself anyway.
