### ISSUE TITLE
add version flag

### ISSUE THREAD

**Issue by tmcw** [mapbox/geobuf#9]
Though [protobuf supports evolving schemas](https://developers.google.com/protocol-buffers/docs/proto#updating) it may be good to have an explicit version too.

**Comment by joto** [comment]
:+1: The protobuf versioning is on a different "level" than the format versioning. It could well be that we want a different geobuf version that interprets the same protobuf format in a different way. Or that we don't want to change the geobuf version because we add an optional extra field in the protobuf format that everybody can ignore.

**Comment by tmcw** [comment]
@mourner do you think geobuf should encode a version field, or can we rely on protobuf itself for this?

**Comment by mourner** [comment]
@tmcw yes. I think we should add it for the reasons @joto stated. We can do this as a part of the next big revision of the format (e.g. I added the field in sample schemas in #51).

**Comment by tmcw** [comment]
Not seeing any movement here. Feel free to reopen but I'd prefer not to own this issue.
